# Generated by Django 4.2.7 on 2023-11-28 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='youtube_link',
            field=models.URLField(blank=True),
        ),
    ]
