# Generated by Django 4.2.7 on 2024-08-12 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_contactinfo_whatsapp_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='linkedin_link',
            field=models.URLField(blank=True),
        ),
    ]
