# Generated by Django 4.2.7 on 2023-12-19 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='additionalimage',
            old_name='additional_images',
            new_name='image',
        ),
    ]
