# Generated by Django 4.2.7 on 2024-02-08 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
        ('projects', '0004_rename_additional_images_additionalimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='services',
            field=models.ManyToManyField(to='services.service'),
        ),
    ]
