# Generated by Django 4.2.7 on 2024-02-14 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
        ('projects', '0005_project_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='services',
            field=models.ManyToManyField(blank=True, to='services.service'),
        ),
    ]
