# Generated by Django 4.2.7 on 2024-02-23 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_project_services'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-rank']},
        ),
        migrations.AddField(
            model_name='project',
            name='rank',
            field=models.IntegerField(default=1),
        ),
    ]
