# Generated by Django 4.2.7 on 2024-06-20 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_project_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='walkthrough_link',
            field=models.URLField(blank=True),
        ),
    ]
