# Generated by Django 4.2.7 on 2025-01-19 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_remove_project_description_remove_project_disabled_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['rank']},
        ),
    ]
