# Generated by Django 4.2.7 on 2025-01-20 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_alter_servicevalue_service'),
        ('projects', '0012_project_thumbnail_project_thumbnail_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='services.service'),
        ),
    ]
