version: '3.8'

services:
  web_prod:
    build: .
    command: gunicorn griha.wsgi:application --bind 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - ./.env.prod
    depends_on:
      - db_prod
  db_prod:
    image: postgres:16
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db

volumes:
  postgres_data_prod: