# Generated by Django 4.2.7 on 2024-08-12 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maingallery',
            options={'verbose_name_plural': 'Galleries'},
        ),
        migrations.RenameField(
            model_name='galleryimage',
            old_name='header_image',
            new_name='image',
        ),
    ]
