# Generated by Django 4.2.7 on 2024-08-12 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0002_alter_processstep_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processstep',
            name='process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='process.process'),
        ),
    ]
