# Generated by Django 4.2.7 on 2024-02-07 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('header_image', models.ImageField(upload_to='services/header/')),
                ('slug', models.SlugField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='AdditionalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='services/additional/')),
                ('service', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='services.service')),
            ],
        ),
    ]
