# Generated by Django 4.2.7 on 2025-01-19 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_service_options_service_rank'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='header_image',
            new_name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='service',
            name='description',
        ),
        migrations.RemoveField(
            model_name='service',
            name='summary',
        ),
    ]
