# Generated by Django 4.2.7 on 2025-01-19 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_alter_serviceprocessstep_process'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicevalue',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='services.service'),
        ),
    ]
