# Generated by Django 4.2.7 on 2023-11-28 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_line', models.CharField(max_length=254)),
                ('header_image', models.ImageField(upload_to='homepage/header/')),
                ('header_video', models.FileField(upload_to='homepage/header/')),
            ],
        ),
    ]
