# Generated by Django 4.2.7 on 2023-11-28 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagecontent',
            name='header_video',
            field=models.FileField(blank=True, upload_to='homepage/header/'),
        ),
    ]
