# Generated by Django 4.2.7 on 2023-11-28 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_alter_homepagecontent_header_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagecontent',
            name='header_video',
            field=models.FileField(blank=True, upload_to='media/homepage/header/'),
        ),
    ]
