# Generated by Django 4.2.7 on 2023-11-28 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_alter_homepagecontent_header_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagecontent',
            name='header_image',
            field=models.ImageField(upload_to='homepage/header/'),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='header_video',
            field=models.FileField(blank=True, upload_to='homepage/header/'),
        ),
    ]
