# Generated by Django 4.2.7 on 2024-02-13 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_homepagecontent_fav_icon_homepagecontent_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagecontent',
            name='nav_bar_logo',
            field=models.ImageField(blank=True, upload_to='homepage/header'),
        ),
    ]
