# Generated by Django 4.2.7 on 2024-02-14 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_homepagecontent_nav_bar_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagecontent',
            name='welcome_message',
            field=models.TextField(blank=True),
        ),
    ]
