# Generated by Django 4.2.7 on 2024-08-12 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0009_homepagecontent_welcome_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagecontent',
            name='tag_line',
            field=models.TextField(blank=True),
        ),
    ]
