# Generated by Django 4.2.7 on 2024-08-12 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0010_alter_homepagecontent_tag_line'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_image', models.ImageField(blank=True, upload_to='homepage/about/')),
                ('summary', models.TextField()),
                ('home_page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='homepage.homepagecontent')),
            ],
        ),
    ]
