# Generated by Django 4.2.7 on 2024-08-12 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0011_aboutcontent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepagecontent',
            old_name='nav_bar_logo',
            new_name='small_logo',
        ),
    ]
