# Generated by Django 4.2.7 on 2024-12-12 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0012_rename_nav_bar_logo_homepagecontent_small_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutcontent',
            name='tagline',
            field=models.TextField(blank=True),
        ),
    ]
