# Generated by Django 4.2.7 on 2024-12-14 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0014_remove_aboutcontent_tagline_tagline'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagline',
            name='footer',
            field=models.TextField(blank=True),
        ),
    ]
