# Generated by Django 4.2.7 on 2024-12-20 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0016_virtualwalkthrough'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualwalkthrough',
            name='home_page',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='homepage.homepagecontent'),
            preserve_default=False,
        ),
    ]
