# Generated by Django 4.2.7 on 2025-01-19 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0018_alter_homepagecontent_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagecontent',
            name='logo_white',
            field=models.ImageField(blank=True, upload_to='homepage/header'),
        ),
    ]
