# Generated by Django 4.2.7 on 2023-11-28 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_review_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_image', models.ImageField(upload_to='reviews/header/')),
            ],
        ),
    ]
