# Generated by Django 4.2.7 on 2023-12-18 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_name'),
        ('reviews', '0003_reviewpagecontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='project',
            field=models.ManyToManyField(to='projects.project'),
        ),
    ]
