# Generated by Django 4.2.7 on 2024-02-23 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_remove_review_project_review_project'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-rank']},
        ),
        migrations.AddField(
            model_name='review',
            name='rank',
            field=models.IntegerField(default=1),
        ),
    ]
